docker_builder:
  name: Build and Push
  env:
    DOCKER_USER: ENCRYPTED[70de3eab8012934af29396b59fb0152028d44745035fb422ca4ebba562e5907ef5b266274c39043577a6f6fa40b9b73b]
    DOCKER_PASS: ENCRYPTED[4c67a69253fd666eb2e4f5ad1a3675ac9e3e6e39023bfcfdbbd6528ff3a79537b2ed5e0af0daee226a20bdc307f2603b]
  build_script: GIT_BRANCH=$CIRRUS_BRANCH make
  test_script: GIT_BRANCH=$CIRRUS_BRANCH make test
  version_script: GIT_BRANCH=$CIRRUS_BRANCH make version
  login_script: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  push_script: GIT_BRANCH=$CIRRUS_BRANCH make push
