docker_builder:
  name: Build
  build_script: GIT_BRANCH=$CIRRUS_BRANCH make

docker_builder:
  name: Test
  test_script: GIT_BRANCH=$CIRRUS_BRANCH make test

docker_builder:
  name: Version
  info_script: GIT_BRANCH=$CIRRUS_BRANCH make version

docker_builder:
  name: Docker Login
  login_script: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

docker_builder:
  name: Push
  push_script: GIT_BRANCH=$CIRRUS_BRANCH make push
